### ISSUE TITLE
Osiobe Mirabel Ogheneruona

### ISSUE THREAD

**Issue by ElSam20** [zuri-training/AuthWiki_Team4#119]

**Comment by MirabelOsiobe** [comment]
LO - FI SCREENS

SETTINGS PAGE DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2088%3A4035

SETTINGS PAGE MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4641

DELETE PROFILE DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2388%3A3960

DELETE PROFILE MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2388%3A5896

PROFILE SAVED DESKTOP
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2388%3A4122

PROFILE SAVED MOBILE
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2388%3A6042

**Comment by MirabelOsiobe** [comment]
HI - FI SCREENS

SETTINGS PAGE DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2393%3A4153

SETTINGS PAGE MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4645

DELETE PROFILE DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2581%3A4773

DELETE PROFILE MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2588%3A5028

PROFILE SAVED DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2581%3A4891

PROFILE SAVED MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2610%3A5174

**Comment by MirabelOsiobe** [comment]
HOME PAGE LO-FI AND HIFI 
DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4638

https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1714%3A1799

MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1716%3A2023

https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1718%3A1752

**Comment by MirabelOsiobe** [comment]
#35 
#30
#95 

1. Designed the button system
2. Designed the settings page for both desktop and mobile screens (lo-fi and Hi-fi)
3. Designed the home page for both desktop and mobile screens (lo-fi and Hi-fi) with @yewandefajem 
4. Designed the delete profile page and profile saved page which is part of the settings page.
