### ISSUE TITLE
Chjioke Emechebe

### ISSUE THREAD

**Issue by ElSam20** [zuri-training/AuthWiki_Team4#121]

**Comment by esamueljsx** [comment]
https://github.com/zuri-training/AuthWiki_Team4/issues/72 

https://github.com/zuri-training/AuthWiki_Team4/issues/71 

https://github.com/zuri-training/AuthWiki_Team4/issues/38 

https://github.com/zuri-training/AuthWiki_Team4/issues/35 

https://github.com/zuri-training/AuthWiki_Team4/issues/33 

https://github.com/zuri-training/AuthWiki_Team4/issues/31

1. Designed Landing page HI-FI for Desktop and Mobile screen
2. Designed Login and Email Verification HI-FI for Desktop and Mobile screen
3. Designed Login and Sigup screens
4. Designed the Landing page
5. Designed the design system with other designers
