### ISSUE TITLE
Fajemilugba Yewande

### ISSUE THREAD

**Issue by ElSam20** [zuri-training/AuthWiki_Team4#122]

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1714%3A1799 (Homepage desktop view)

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4642 (profile page Desktop view)

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1714%3A1799 (Homepage Desktop view)

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4643 (Homepage mobile view)

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4644 (profile page mobile view)
