### ISSUE TITLE
Afolayan Daniel Toluwalase

### ISSUE THREAD

**Issue by ElSam20** [zuri-training/AuthWiki_Team4#124]

**Comment by ti-oluwa** [comment]
- #33

**Comment by ti-oluwa** [comment]
# Below is a list of completed tasks showing my contributions to this repository

- __#81 *(Completed with commits made in PR #102 and #130)*.__
##
- __#131 *(Completed in PR #130)*.__
##
- __#42 *(Completed in PR #68 and PR #82)*.__
##
- __#92 *(Completed with commits made in PR #130 )*.__
##
- __#80 *(Completed in PR #130 also)*.__
##
- __#162 *(Initiated in PR #142 & Completed in PR #154)*__
##
- __I was also assigned to set up the team's repository and worked on the project board likewise.__
##
- __Wrote the project and repository's README (PR #18,  #19... and other PR's were made to complete this).__ 
##
> ## __*You can also view [my github profile](https://github.com/ti-oluwa) for an overview of my contributions to this repository*__.
