### ISSUE TITLE
Design Home Page - Lo-Fi, Hi-Fi and mobile screens

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#30]
# Refer to #29 for an overview of all design related tasks

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1714%3A1799

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1714%3A1799 @ElSam20

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1718%3A1752 @ElSam20

**Comment by yewandefajem** [comment]
Am I supposed to upload on this?

**Comment by MirabelOsiobe** [comment]
LO - FI SCREENS
DESKTOP
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4638

MOBILE
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=1716%3A2023
