### ISSUE TITLE
Design Signup Screen

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#33]
# Refer to #29 for an overview of all design related tasks

**Comment by esamueljsx** [comment]
The signup screen has been created successfully 

Please review the design

**Comment by esamueljsx** [comment]
[Signup and Login screens for review](https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=155%3A34)

**Comment by ti-oluwa** [comment]
Design reviewed and accepted
