### ISSUE TITLE
Design Library Page

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#34]
# Refer to #29 for an overview of all design related tasks

**Comment by SimplyBeck** [comment]
Done

https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=155%3A34

**Comment by ti-oluwa** [comment]
@Abayolpeter Please review and close with 'Reviewed and accepted'
Also change this issue's status to 'Done'.

**Comment by SimplyBeck** [comment]
@Abayolpeter Done

https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=155%3A34
