### ISSUE TITLE
Design System - Fields, Toasts & Buttons

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#35]
# Refer to #29 for an overview of all design related tasks

**Comment by Samandcode** [comment]
It's has been completed and open for review

[Login screen ](https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=492%3A411)

**Comment by Meenahbel** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=17%3A2
