### ISSUE TITLE
Design Login Screen

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#38]
# Refer to #29 for an overview of all design related tasks

**Comment by esamueljsx** [comment]
It has been completed and open for review 

[Login screen ](https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=492%3A411)

**Comment by ti-oluwa** [comment]
Design reviewed and accepted
