### ISSUE TITLE
Develop Content for authentication code's detail view

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#49]
# You are to develop content for each authentication code detail page
## Refer to this [doc](https://docs.google.com/document/d/1abw8w5jxAbgRArFsZvEcatSDMBtzwYKcDNJYkmgjvNc/edit?usp=drivesdk) for the format to use for structuring you tasks
__Your should submit a google doc link in this thread after the task has been completed__
# Refer to #1 for an overview of all frontend related tasks

**Comment by chigozieokoroafor** [comment]
@ti-oluwa, i am sort of confused as regards to the issue's title, but correct me if i'm wrong, i should make separate auths codes that would be used

**Comment by ti-oluwa** [comment]
No sir. You guys would be developing content for each authentication code's detail (download) page. You should already have one you're working on and if you have finished working on it, post a link to the doc in this thread

**Comment by starlingvibes** [comment]
https://docs.google.com/document/d/1XXbCB4qmGQXV7qRv_HlKXw3-9_ETbifYzXce2a-cAQM/edit?usp=sharing

**Comment by Emzard** [comment]
https://docs.google.com/document/d/1x21sflI5mGdH_jMBwRPSLHfuMBY6usI_19ZRFfLNeRw/edit?usp=sharing

**Comment by yusfate4** [comment]
https://docs.google.com/document/d/1SSR_etx-WEGDnxJGLkyFU37dUHsD1XrVoFwiUXoWMYc/edit?usp=sharing

Please, kindly check for review

**Comment by ti-oluwa** [comment]
> https://docs.google.com/document/d/1SSR_etx-WEGDnxJGLkyFU37dUHsD1XrVoFwiUXoWMYc/edit?usp=sharing
> 
> Please, kindly check for review


It's okay but I think the application example and code snippet still needs improvement.
@ElSam20 What do you reckon?

**Comment by chigozieokoroafor** [comment]
https://docs.google.com/document/d/1kyg08hBa5RUD3vjoY_d9-cTWAKG02h4m/edit?usp=sharing&ouid=104735513871091929134&rtpof=true&sd=true

**Comment by ti-oluwa** [comment]
> https://docs.google.com/document/d/1kyg08hBa5RUD3vjoY_d9-cTWAKG02h4m/edit?usp=sharing&ouid=104735513871091929134&rtpof=true&sd=true

Is this authentication code detail for PyOtp or Send Grid because I can see Send Grid which is used to manage emails?
Please make your doc more detailed so we can decipher what it's actually about.

**Comment by chigozieokoroafor** [comment]
https://docs.google.com/document/d/1YvGrH5qUSFWupC6jgJ2HbWcDtSbysAISoSdxNO-uLRc/edit?usp=sharing

Kindly check for review

**Comment by yusfate4** [comment]
https://docs.google.com/document/d/1SSR_etx-WEGDnxJGLkyFU37dUHsD1XrVoFwiUXoWMYc/edit?usp=sharing

Good evening. Kindly help me to check for review. Thanks

**Comment by Emzard** [comment]
https://docs.google.com/document/d/1x21sflI5mGdH_jMBwRPSLHfuMBY6usI_19ZRFfLNeRw/edit?usp=sharing

Updated the document to include formatted code snippets.

**Comment by ti-oluwa** [comment]
> https://docs.google.com/document/d/1x21sflI5mGdH_jMBwRPSLHfuMBY6usI_19ZRFfLNeRw/edit?usp=sharing
> 
> Updated the document to include formatted code snippets.

Thanks your submission has been accepted

**Comment by ElSam20** [comment]
> https://docs.google.com/document/d/1YvGrH5qUSFWupC6jgJ2HbWcDtSbysAISoSdxNO-uLRc/edit?usp=sharing
> 
> Kindly send the link to the repo where you're hosting the Authentication code

**Comment by chigozieokoroafor** [comment]
I would push the codes to github and send the repo link this evening, currently now around my laptop , I would add it to the Google doc and inform you

**Comment by chigozieokoroafor** [comment]
https://github.com/chigozieokoroafor/authendtications/blob/main/auth_codes_wiki.py #
