### ISSUE TITLE
Develop authentication code

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#50]
# This issue is for those developing their own authentication code to be included in AuthWiki's library

__You can submit your code by dropping the link to its repo in the thread. You are also expected to develop content for your code based on #49__

# Refer to #1 for an overview of all frontend related tasks

**Comment by starlingvibes** [comment]
https://github.com/starlingvibes/I4GxZuri-NodeJS/tree/main/Auth%20library

**Comment by starlingvibes** [comment]
https://github.com/scotch-io/easy-node-authentication

**Comment by starlingvibes** [comment]
https://github.com/scotch-io/node-token-authentication.git

**Comment by ti-oluwa** [comment]
> https://github.com/scotch-io/easy-node-authentication

This submission is not related to this issue. You're expected to submit a link to authentication code you developed yourself. This would still be taken in as a suggestion.

**Comment by ti-oluwa** [comment]
> https://github.com/starlingvibes/I4GxZuri-NodeJS/tree/main/Auth%20library

Your submission has been accepted. But you're also expected to develop content detailing how this code can be used based on #49 (Please endeavor to include the link to the code's repository in the doc you submit.)
Thanks

**Comment by ti-oluwa** [comment]
> https://github.com/scotch-io/node-token-authentication.git

This submission is not related to this issue. You're expected to submit a link to authentication code you developed yourself. This would still be taken in as a suggestion.

**Comment by starlingvibes** [comment]
> > [starlingvibes/I4GxZuri-NodeJS@`main`/Auth%20library](https://github.com/starlingvibes/I4GxZuri-NodeJS/tree/main/Auth%20library?rgh-link-date=2022-07-31T10%3A02%3A37Z)
> 
> Your submission has been accepted. But you're also expected to develop content detailing how this code can be used based on #49 (Please endeavor to include the link to the code's repository in the doc you submit.) Thanks

I've updated the document accordingly: https://docs.google.com/document/d/1XXbCB4qmGQXV7qRv_HlKXw3-9_ETbifYzXce2a-cAQM/edit?usp=sharing

**Comment by ti-oluwa** [comment]
> > > [starlingvibes/I4GxZuri-NodeJS@`main`/Auth%20library](https://github.com/starlingvibes/I4GxZuri-NodeJS/tree/main/Auth%20library?rgh-link-date=2022-07-31T10%3A02%3A37Z)
> > 
> > Your submission has been accepted. But you're also expected to develop content detailing how this code can be used based on #49 (Please endeavor to include the link to the code's repository in the doc you submit.) Thanks
> 
> I've updated the document accordingly: https://docs.google.com/document/d/1XXbCB4qmGQXV7qRv_HlKXw3-9_ETbifYzXce2a-cAQM/edit?usp=sharing

I just took a look at it, its the same as the one you submitted under issue #49. Is this the code you submitted content for there?

**Comment by starlingvibes** [comment]
> > > > [starlingvibes/I4GxZuri-NodeJS@`main`/Auth%20library](https://github.com/starlingvibes/I4GxZuri-NodeJS/tree/main/Auth%20library?rgh-link-date=2022-08-02T09%3A58%3A32Z)
> > > 
> > > 
> > > Your submission has been accepted. But you're also expected to develop content detailing how this code can be used based on #49 (Please endeavor to include the link to the code's repository in the doc you submit.) Thanks
> > 
> > 
> > I've updated the document accordingly: [docs.google.com/document/d/1XXbCB4qmGQXV7qRv_HlKXw3-9_ETbifYzXce2a-cAQM/edit?usp=sharing](https://docs.google.com/document/d/1XXbCB4qmGQXV7qRv_HlKXw3-9_ETbifYzXce2a-cAQM/edit?usp=sharing)
> 
> I just took a look at it, its the same as the one you submitted under issue #49. Is this the code you submitted content for there?

It's not the same, I updated it with authentication codes for social sign-on (github, facebook and google)

**Comment by chigozieokoroafor** [comment]
Would reformat it

**Comment by chigozieokoroafor** [comment]
https://docs.google.com/document/d/1YvGrH5qUSFWupC6jgJ2HbWcDtSbysAISoSdxNO-uLRc/edit?usp=sharing

Kindly check this for a review
