### ISSUE TITLE
Design authentication code detail page - Hi-Fi and mobile screens

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#74]
# Refer to #29 for an overview of all design related tasks

**Comment by SimplyBeck** [comment]
@Abayolpeter @ti-oluwa . This has been done since

https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=370%3A1985

**Comment by ti-oluwa** [comment]
Was expecting you to submit a link before I close it

**Comment by SimplyBeck** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=370%3A1985
