### ISSUE TITLE
Develop Error pages

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#80]
## You are to write the markup for and style the following error pages using the designs you'll find on [this](https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=370%3A1985) page
- __404__ 
- __403__
- __500__

**Comment by theabdullahishola** [comment]
github.com/theabdullahishola/error

**Comment by ti-oluwa** [comment]
# Fixed in PR #130
