### ISSUE TITLE
Design the Profile page - LoFi, Hi-Fi and mobile

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#94]

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2161%3A2929 @ElSam20

**Comment by yewandefajem** [comment]
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2161%3A3133 @ElSam20

**Comment by ti-oluwa** [comment]
Reviewed and accepted
