### ISSUE TITLE
Design the settings page - LoFi, Hi-Fi and mobile

### ISSUE THREAD

**Issue by ti-oluwa** [zuri-training/AuthWiki_Team4#95]

**Comment by MirabelOsiobe** [comment]
LO - FI SCREENS

SETTINGS PAGE DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2088%3A4035

SETTINGS PAGE MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4641

DELETE PROFILE DESKTOP SCREEN 
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2388%3A3960


DELETE PROFILE MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2388%3A5896

PROFILE SAVED DESKTOP
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2388%3A4122

PROFILE SAVED MOBILE
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2388%3A6042

**Comment by MirabelOsiobe** [comment]
HI - FI SCREENS

SETTINGS PAGE DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2393%3A4153

SETTINGS PAGE MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2669%3A4645

DELETE PROFILE DESKTOP SCREEN 
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2581%3A4773


DELETE PROFILE MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2588%3A5028

PROFILE SAVED DESKTOP SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2581%3A4891

PROFILE SAVED MOBILE SCREEN
https://www.figma.com/file/UzdIIpsX43I1ZgMETPwLgQ/Authentication-Library?node-id=2610%3A5174
